coverage:
  status:
    project:
      default: false
      tests:
        target: 0%
        paths:
          - "potatocountry/src"
        threshold: 0%      # 허용되는 감소 범위
        if_ci_failed: error     # CI 실패시 에러 표시
    patch:
      default:
        target: 0%
        threshold: 0%
        if_ci_failed: error