services:
  #  spring-app:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    container_name: potato-app
  #    ports:
  #      - "8080:8080"
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-potato:3306/potatodb
  #      - SPRING_DATASOURCE_USERNAME=root
  #      - SPRING_REDIS_HOST=redis-potato
  #      - SPRING_REDIS_PORT=6379
  #    depends_on:
  #      - mysql-potato
  #      - redis-potato

  mysql-potato:
    image: mysql:latest
    container_name: mysql-potato
    ports:
      - "4306:3306"
    environment:
      - MYSQL_DATABASE=potatodb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql-data:/var/lib/mysql

  redis-potato:
    image: redis:latest
    container_name: redis-potato
    ports:
      - "4379:6379"

volumes:
  mysql-data:
