spring:
  application:
    name: potatocountry
  h2:
    console:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
