name: 📊 Run tests and upload coverage
run-name: ${{ github.actor }} is Code cov 🚀
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

defaults:
  run:
    working-directory: ./potatocountry

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: |
          ./gradlew test jacocoTestReport
          if [ $? -ne 0 ]; then
            echo "Tests failed"
            exit 1
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/customJacocoReportDir/test/jacocoTestReport.xml